import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Shield, FileText, Mail } from 'lucide-react'

// ── Modal ────────────────────────────────────────────────────────────────────

function Modal({ title, children, onClose }: {
  title: string
  children: React.ReactNode
  onClose: () => void
}) {
  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="absolute inset-0 bg-plum/30 backdrop-blur-sm"
          onClick={onClose}
          aria-hidden="true"
        />
        <motion.div
          initial={{ opacity: 0, y: 24, scale: 0.97 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 12 }}
          transition={{ duration: 0.22, ease: 'easeOut' }}
          className="relative rose-card w-full max-w-2xl max-h-[80vh] overflow-hidden flex flex-col z-10"
          role="dialog"
          aria-modal="true"
          aria-label={title}
        >
          {/* Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-pink/40">
            <h2 className="font-display text-base font-semibold text-plum">{title}</h2>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-lg bg-blush flex items-center justify-center hover:bg-pink/50 transition-colors"
              aria-label="Close"
            >
              <X className="w-4 h-4 text-plum" aria-hidden />
            </button>
          </div>
          {/* Content */}
          <div className="overflow-y-auto px-6 py-5 prose-rose text-sm space-y-4 leading-relaxed">
            {children}
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  )
}

// ── Terms of Service ──────────────────────────────────────────────────────────

function TermsContent() {
  return (
    <>
      <p className="text-plum-muted text-xs">Last updated: June 2026</p>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">1. Acceptance of Terms</h3>
        <p className="text-plum/80">By accessing or using Lumen ("the Service"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not access the Service.</p>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">2. Description of Service</h3>
        <p className="text-plum/80">Lumen is an AI-powered video analysis tool that generates structured notes, visual scene descriptions, and conversational Q&A from uploaded videos or YouTube URLs. The Service is provided for personal, educational, and non-commercial research purposes.</p>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">3. User Responsibilities</h3>
        <ul className="list-disc pl-5 text-plum/80 space-y-1">
          <li>You may only upload or process content for which you hold the necessary rights or permissions.</li>
          <li>You must not use the Service to process, distribute, or analyse content that is illegal, defamatory, obscene, or infringes on any third-party intellectual property rights.</li>
          <li>You are solely responsible for the videos you submit and the notes generated from them.</li>
          <li>You agree not to use automated tools, bots, or scripts to abuse the Service or circumvent rate limits.</li>
        </ul>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">4. AI-Generated Content</h3>
        <p className="text-plum/80">Notes, summaries, and answers generated by the Service are produced by artificial intelligence models and may contain inaccuracies. Lumen makes no warranties as to the accuracy, completeness, or fitness for any particular purpose of AI-generated content. You should independently verify any information before relying on it.</p>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">5. Third-Party Services</h3>
        <p className="text-plum/80">The Service uses third-party providers including Groq (AI inference), Supabase (authentication and database), and yt-dlp (video retrieval). By using the Service you also agree to be bound by their respective terms of service and acceptable use policies. We are not responsible for the practices of any third-party service.</p>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">6. Prohibited Uses</h3>
        <p className="text-plum/80">You agree not to use the Service to:</p>
        <ul className="list-disc pl-5 text-plum/80 space-y-1">
          <li>Process content that violates copyright, trademark, or other intellectual property laws.</li>
          <li>Engage in bulk or automated processing without prior written consent.</li>
          <li>Attempt to reverse-engineer, probe, or exploit the Service's infrastructure.</li>
          <li>Share your account credentials or API tokens with unauthorized parties.</li>
        </ul>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">7. Limitation of Liability</h3>
        <p className="text-plum/80">To the maximum extent permitted by law, Lumen and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, the Service — including but not limited to loss of data, loss of profits, or business interruption.</p>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">8. Service Availability</h3>
        <p className="text-plum/80">We do not guarantee continuous, uninterrupted, or error-free access to the Service. We reserve the right to modify, suspend, or discontinue the Service at any time without notice.</p>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">9. Changes to Terms</h3>
        <p className="text-plum/80">We reserve the right to update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
      </section>
    </>
  )
}

// ── Privacy Policy ────────────────────────────────────────────────────────────

function PrivacyContent() {
  return (
    <>
      <p className="text-plum-muted text-xs">Last updated: June 2026</p>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">1. Information We Collect</h3>
        <p className="text-plum/80">We collect only what is necessary to provide the Service:</p>
        <ul className="list-disc pl-5 text-plum/80 space-y-1">
          <li><strong>Account information:</strong> Email address, provided at sign-up via Supabase Auth.</li>
          <li><strong>Video content:</strong> Files you upload or URLs you submit for processing. These are stored temporarily to run the pipeline and then served back to you.</li>
          <li><strong>Generated data:</strong> AI-generated notes, transcripts, scene descriptions, and FAISS search indexes associated with your account.</li>
          <li><strong>Usage metadata:</strong> Request timestamps and job statuses, used solely for rate limiting and quota management.</li>
        </ul>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">2. How We Use Your Data</h3>
        <ul className="list-disc pl-5 text-plum/80 space-y-1">
          <li>To process your videos and generate notes on your behalf.</li>
          <li>To authenticate your session and enforce per-user data isolation.</li>
          <li>To enforce rate limits and prevent abuse of third-party AI APIs.</li>
          <li>We do not sell, share, or disclose your data to any third party except as required to deliver the Service (e.g., sending audio to Whisper for transcription, keyframes to Groq Vision for scene description).</li>
        </ul>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">3. Data Isolation & Security</h3>
        <p className="text-plum/80">Each user's data is isolated via Row-Level Security policies enforced at the database level (Supabase PostgreSQL). Only you can access your videos, notes, and transcripts. We use HMAC-signed tokens for media access and Bearer JWT authentication for all API requests. All data in transit is encrypted via HTTPS/TLS.</p>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">4. Third-Party Data Processors</h3>
        <p className="text-plum/80">We use the following processors to deliver the Service:</p>
        <ul className="list-disc pl-5 text-plum/80 space-y-1">
          <li><strong>Supabase</strong> — authentication and PostgreSQL database hosting.</li>
          <li><strong>Groq</strong> — AI inference for video note generation and scene description (text and image data is transmitted to Groq's API).</li>
          <li><strong>Redis (self-hosted)</strong> — session caching and task queuing; no personal data stored.</li>
        </ul>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">5. Data Retention</h3>
        <p className="text-plum/80">Uploaded video files and keyframes are retained for as long as your account is active. Generated notes and transcripts are stored indefinitely so you can revisit them. You can delete your account at any time to remove all associated data from our systems.</p>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">6. Cookies & Local Storage</h3>
        <p className="text-plum/80">We use browser <code className="font-mono text-xs bg-pink/30 px-1 rounded">localStorage</code> to store your authentication session token. No third-party tracking cookies are used. We do not run any advertising networks or analytics SDKs.</p>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">7. Your Rights</h3>
        <p className="text-plum/80">You have the right to access, correct, or delete the personal data we hold about you. To exercise these rights, please contact us at the email below. We will respond within 30 days.</p>
      </section>

      <section>
        <h3 className="font-display font-semibold text-plum text-base mb-1">8. Contact</h3>
        <p className="text-plum/80">
          Email: <a href="mailto:salonisinghsohar@gmail.com" className="text-prune hover:underline">salonisinghsohar@gmail.com</a><br />
          Phone: <a href="tel:+917042728705" className="text-prune hover:underline">+91 70427 28705</a>
        </p>
      </section>
    </>
  )
}

// ── Footer component ──────────────────────────────────────────────────────────

export default function Footer() {
  const [modal, setModal] = useState<'terms' | 'privacy' | null>(null)
  const year = new Date().getFullYear()

  return (
    <>
      <footer className="mt-auto border-t border-pink/40 bg-cream/60 backdrop-blur-sm">
        <div className="max-w-5xl mx-auto px-4 py-10">
          {/* Top row */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-8 mb-8">
            {/* Brand */}
            <div>
              <span className="font-script text-2xl text-prune block mb-2">Lumen</span>
              <p className="text-xs text-plum-muted leading-relaxed max-w-xs">
                AI-powered video intelligence. Upload any video and get structured notes,
                semantic search, and a conversational assistant — all from one video.
              </p>
            </div>

            {/* Product */}
            <div>
              <p className="text-xs font-semibold text-plum uppercase tracking-widest mb-3">Product</p>
              <ul className="space-y-2 text-xs text-plum-muted">
                <li>Multimodal AI — audio + visual</li>
                <li>Semantic search with FAISS</li>
                <li>Lumen conversational Q&A</li>
                <li>Scene detection & keyframes</li>
                <li>PDF export</li>
              </ul>
            </div>

            {/* Legal & contact */}
            <div>
              <p className="text-xs font-semibold text-plum uppercase tracking-widest mb-3">Legal & Contact</p>
              <ul className="space-y-2 text-xs">
                <li>
                  <button
                    onClick={() => setModal('terms')}
                    className="text-plum-muted hover:text-prune transition-colors"
                  >
                    Terms of Service
                  </button>
                </li>
                <li>
                  <button
                    onClick={() => setModal('privacy')}
                    className="text-plum-muted hover:text-prune transition-colors"
                  >
                    Privacy Policy
                  </button>
                </li>
                <li>
                  <a
                    href="mailto:salonisinghsohar@gmail.com"
                    className="text-plum-muted hover:text-prune transition-colors flex items-center gap-1"
                  >
                    <Mail className="w-3 h-3" aria-hidden />
                    salonisinghsohar@gmail.com
                  </a>
                </li>
                <li>
                  <a
                    href="tel:+917042728705"
                    className="text-plum-muted hover:text-prune transition-colors flex items-center gap-1"
                  >
                    <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                      <path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07A19.5 19.5 0 014.69 11.5a19.79 19.79 0 01-3.07-8.67A2 2 0 013.61 2h3a2 2 0 012 1.72c.127.96.361 1.903.7 2.81a2 2 0 01-.45 2.11L7.91 9.91a16 16 0 006.18 6.18l1.28-.935a2 2 0 012.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0122 16.92z"/>
                    </svg>
                    +91 70427 28705
                  </a>
                </li>
              </ul>
            </div>
          </div>

          {/* Divider */}
          <div className="border-t border-pink/40 pt-5 flex flex-col sm:flex-row items-center justify-between gap-3">
            <p className="text-xs text-plum-muted">
              © {year} Lumen — AI Video Summarizer. All rights reserved.
            </p>
            <div className="flex items-center gap-1.5 text-xs text-plum-muted">
              <Shield className="w-3 h-3 text-prune/60" aria-hidden />
              <span>Your data is encrypted and private to your account.</span>
            </div>
          </div>
        </div>
      </footer>

      {/* Modals */}
      {modal === 'terms' && (
        <Modal title="Terms of Service" onClose={() => setModal(null)}>
          <TermsContent />
        </Modal>
      )}
      {modal === 'privacy' && (
        <Modal title="Privacy Policy" onClose={() => setModal(null)}>
          <PrivacyContent />
        </Modal>
      )}
    </>
  )
}
